---
- name: Install Zabbix Server on Ubuntu
  hosts: server
  become: true

  tasks:
    - name: Download Zabbix repository
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb
        dest: /tmp/zabbix-release_latest+ubuntu24.04_all.deb

    - name: Install Zabbix repository package
      ansible.builtin.apt:
        deb: /tmp/zabbix-release_latest+ubuntu24.04_all.deb

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Zabbix server, frontend, and agent
      ansible.builtin.apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
        update_cache: yes

    - name: Clean up downloaded repository package
      ansible.builtin.file:
        path: /tmp/zabbix-release_latest+ubuntu24.04_all.deb
        state: absent

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
